################################################################################

SCP      = scp
USER     = coder_1024
HOST     = multiping.sourceforge.net
DESTPATH = /home/groups/m/mu/multiping/htdocs

################################################################################

WEBFILES = \
	index.html

################################################################################

default:
	$(SCP) $(WEBFILES) $(USER)@$(HOST):$(DESTPATH)



